### ISSUE TITLE
Feature Request: Lock until a batch is completed

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#5803]
Hi there!

I have a specific job that processes hundreds of thousands of records every 5 minutes, like this:

```ruby
class MyJob
  include Sidekiq::Job
  sidekiq_options queue: "heavy", unique_for: 1.hour

  def perform_async
    Model.in_batches do |batch|
      processed_batch = do_something(batch)
      Model.upsert_all(processed_batch)
    end
  end
end
```

Looking into optimizing and scaling it, I'm now creating a batch:

```ruby
class MyJob
  include Sidekiq::Job
  sidekiq_options queue: "heavy", unique_for: 1.hour

  def perform_async
    batch = Sidekiq::Batch.new
    batch.description = "#{self.class.name} (started #{Time.zone.now})"
    batch.jobs do
      Model.in_batches do |batch|
        MyJobBatch.perform_async(batch.pluck(:id))
      end
    end
  end
end

class MyJobBatch
  include Sidekiq::Job
  sidekiq_options queue: "heavy", unique_for: 12.hours

  def perform_async(ids)
    batch = Model.where(id: ids)
    processed_batch = do_something(batch)
    Model.upsert_all(processed_batch)
  end
end
```

But then the locking mechanism doesn't fit anymore since after completing the job, the lock is released.

The lock on the MyJobBatch doesn't make sense either since ids might change from run to run.

I'm not sure how we could handle a locking mechanism here where I don't want this job to ever run concurrently but also be safe about poison pills thus allowing it to run after 1 hour of the last try.

**Comment by mperham** [comment]
I think the concurrent rate limiter would be a good choice here. Setting its name to the BID and size to `1` gives you a distributed Mutex for that batch.

https://github.com/sidekiq/sidekiq/wiki/Ent-Rate-Limiting#concurrent

**Comment by sobrinho** [comment]
Not quite, it would limit 1 concurrently job inside the batch but it wouldn't prevent a second MyJob from running.

The specific need (maybe too specific?) is to not allow another MyJob being enqueued until the created batch finishes, but I don't want to limit the concurrent number of jobs inside the batch itself.

**Comment by mperham** [comment]
Another possible idea is to create a flag in Redis upon batch creation and then have the success callback remove that flag. You'll need to worry about TTL, crashes and job failures.

I don't provide any tools for locks which live across process boundaries. That's very app-specific.

**Comment by pantastic-matt** [comment]
> The specific need ... is to not allow another MyJob being enqueued until the created batch finishes

Assuming `MyJob` is a periodic job kicked off at a set interval against all `Model` records as you described, it might be easier to prevent `MyJob` from doing any work if a batch is still processing -- just have it complete successfully with no work done.

A basic approach could use the API [to enumerate active batches](https://github.com/sidekiq/sidekiq/wiki/Batches#api) and [evaluate the status](https://github.com/sidekiq/sidekiq/wiki/Batches#status) of the last `MyJob` batch (can match on batch description, or store MyJob batch IDs). Two callouts here:
1. To prevent race conditions, all logic in `MyJob` that checks for previous batches and creates new batches would need to be in a mutex, for which you could use the concurrent limiter Mike mentioned, but named for the `MyJob` class.
2. In the event some jobs in the batch fail, you may want to [cancel the batch](https://github.com/sidekiq/sidekiq/wiki/Batches#canceling-a-batch) on the completion callback, since that will let the next scheduler queue everything up again once the failed jobs retry and complete.

Another thought is that with `MyJobBatch` dealing with blocks of 1000 records, it may be possible for a single "bad record" to repeatedly block updates of the same 1000 records across iterations. This will be less visible when you go wide and cancel batches on completion than it was when a single "bad record" failed the entire job, so you will want to be comfortable with your alerting/error notification strategy to ensure issues don't go unnoticed.

**Comment by mbar0** [comment]
> The specific need ... is to not allow another MyJob being enqueued until the created batch finishes

Assuming `MyJob` is a periodic job kicked off at a set interval against all `Model` records as you described, it might be easier to prevent `MyJob` from doing any work if a batch is still processing -- just have it complete successfully with no work done.

A basic approach could use the API [to enumerate active batches](https://github.com/sidekiq/sidekiq/wiki/Batches#api) and [evaluate the status](https://github.com/sidekiq/sidekiq/wiki/Batches#status) of the last `MyJob` batch (can match on batch description, or store MyJob batch IDs). Two callouts here:
1. To prevent race conditions, all logic in `MyJob` that checks for previous batches and creates new batches would need to be in a mutex, for which you could use the concurrent limiter Mike mentioned, but named for the `MyJob` class.
2. In the event some jobs in the batch fail, you may want to [cancel the batch](https://github.com/sidekiq/sidekiq/wiki/Batches#canceling-a-batch) on the completion callback, since that will let the next scheduler queue everything up again once the failed jobs retry and complete.

Another thought is that with `MyJobBatch` dealing with blocks of 1000 records, it may be possible for a single "bad record" to repeatedly block updates of the same 1000 records across iterations. This will be less visible when you go wide and cancel batches on completion than it was when a single "bad record" failed the entire job, so you will want to be comfortable with your alerting/error notification strategy to ensure issues don't go unnoticed.

**Comment by sobrinho** [comment]
Both suggestions should be enough to implement something, thanks!

**Comment by palexvs** [comment]
I have a similar issue and came up with such solution:

```
# frozen_string_literal: true

class MainJob < ApplicationJob
  sidekiq_options unique_for: 10.minutes

  def perform(options)
    site_id = options[:site_id]
    if locked?(site_id)
      Rails.logger.info { "#{self.class.name} Is running already (#{options.inspect}" }
      return
    end

    ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, site_id: site_id)
    batch.on(:complete, self.class, site_id: site_id)
    batch.on(:death, self.class, site_id: site_id)

    batch.jobs do
      ids.each do |id|
        SubJob.perform_later(id)
      end
    end

    lock(site_id)
  end

  def on_success(_status, options)
    unlock(options["site_id"])
  end

  def on_complete(_status, options)
    unlock(options["site_id"])
  end

  def on_death(_status, options)
    unlock(options["site_id"])
  end

  private

  def uniq_key(site_id)
    "main_job:#{site_id}:lock"
  end

  def locked?(site_id)
    Rails.cache.read(uniq_key(site_id))
  end

  def lock(site_id)
    Rails.cache.write(uniq_key(site_id), true, expires_in: 10.minutes)
  end

  def unlock(site_id)
    Rails.cache.delete(uniq_key(site_id))
  end
end
```


```
class SubJob < ApplicationJob
  sidekiq_options unique_for: 5.minutes

  def perform(id)
    # Do something
  end
end
```
