### ISSUE TITLE
MemoryDB (single-shard cluster mode) support via Hash Tags

### ISSUE THREAD

**Issue by lorrin** [sidekiq/sidekiq#5899]
# Motivation / Context
Sidekiq [does not support](https://github.com/sidekiq/sidekiq/wiki/Using-Redis#architecture) Redis in cluster mode. AWS has introduced MemoryDB, a managed Redis service that has a very desirable property: all accepted writes are durable. This makes it potentially a great match for Sidekiq. Sidekiq Pro / Enterprise's [super_fetch](https://github.com/sidekiq/sidekiq/wiki/Reliability#using-super_fetch), [reliable_push](https://github.com/sidekiq/sidekiq/wiki/Pro-Reliability-Client), and [reliable_scheduler](https://github.com/sidekiq/sidekiq/wiki/Reliability#scheduler) work together to guarantee that no jobs are lost even if the Ruby process fails. But Sidekiq can't prevent Redis from losing data. Typical Redis deployments do not have durability guarantees. Even in Sentinel mode, Redis replication across servers [is asynchronous](https://redis.io/docs/management/sentinel/#fundamental-things-to-know-about-sentinel-before-deploying) and there is a possibility of data loss. (In MemoryDB, writes are synchronously committed to a multi-AZ transaction log. Redis replication remains asynchronous, but in a fail-over event, a replica will not be promoted to primary until it has caught up from the transaction log. So no data loss even in this scenario.)

# Required Change
Unlike the AWS Elasticache offering, which supports [clustered and non-clustered](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Redis-RedisCluster.html) configurations, MemoryDB only runs in clustered mode, even when configured to have only a single shard. This means keys get hashed and assigned to a slot (and then all slots are are owned by that one node). This causes `CROSSSLOT Keys in request don't hash to the same slot` errors when a single command involves multiple keys that hash to different slots. So there's effectively an API incompatibility between Sidekiq and MemoryDB, even though they would otherwise be a good match. 😞 The Redis [hash-tags](https://redis.io/docs/reference/cluster-spec/#hash-tags) feature provides a work-around: if every key includes a `{foo}` in its name, only `foo` is used to determine the slot, and all keys thus end up in the same slot.

Would it be feasible to have a hashtag setting that causes that hashtag to be injected into every key used by Sidekiq?

----

Ruby version: 3.1.2
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): sidekiq (6.4.0)

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
2023-04-28T06:01:58.817Z pid=90615 tid=24f WARN: Redis::CommandError: CROSSSLOT Keys in request don't hash to the same slot
2023-04-28T06:01:58.817Z pid=90615 tid=24f WARN: /Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis/client.rb:163:in `call'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis/client.rb:257:in `block in call_with_timeout'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis/client.rb:331:in `with_socket_timeout'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis/client.rb:256:in `call_with_timeout'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis.rb:1335:in `block in _bpop'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis.rb:1332:in `_bpop'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.5.1/lib/redis.rb:1377:in `brpop'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/fetch.rb:47:in `block in retrieve_work'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq.rb:100:in `block in redis'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq.rb:97:in `redis'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/fetch.rb:47:in `retrieve_work'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:83:in `get_one'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:95:in `fetch'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:77:in `process_one'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:68:in `run'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:56:in `watchdog'
/Users/lorrin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by mperham** [comment]
Why do you want or need MemoryDB? Is this concern about durability and data loss the main driver?

I did the work necessary to make Enterprise 7.1's Rate Limiting API data model cluster-friendly because that API is very limited in scope. It wasn't difficult once I understood the issue and learned about Hash tagging keys.

On the other hand, Sidekiq's various other APIs use more complex `MULTI` transactions to ensure consistency, which can't spread across servers. I'm not sure it's reasonably possible to modify Sidekiq's data model to suit clustering. How would the Web UI work? Does it scan N cluster members, requiring N lookups for every call?

And for the record, I think you're the first one to ask. I just don't see a lot of demand, the existing services seem to work well enough.

**Comment by lorrin** [comment]
Yes, durability and data loss is the main driver.

I don't think any changes to the data model or web UI are required, just the hash tags in the keys.

To spell that out a bit more: it makes sense to me that Sidekiq requires multi-key transactions. I don't know, but can certainly imagine, that identifying a scheme to assign keys to slots such that only keys from one slot get used together would be tricky. Except for one trivial scheme: put _all_ the keys in the same slot. Now it's only mechanical exercise of prefixing `{1}` into every place a key name is created. (Plus doing it conditionally based on config, so as to not disrupt  people upgrading.) Then MemoryDB can be used to prevent data loss in the case of Redis node / AZ failure. (Obviously, this doesn't enable spreading the load across multiple shards, since all keys will go to the same one.)

**Comment by mperham** [comment]
Yeah, that trivial case is the only immediately obvious "fix" to support clustering. But there are a few cases where I'm not sure how it's possible. I'll think about it over the weekend and write more Monday.

**Comment by mperham** [comment]
The main issue is Sidekiq data which is effectively "global". Things like:

* The set of current processes which are sending heartbeats.
* The scheduled, dead and retry sets.
* The set of known working queues.
* Each queue

For example, when Sidekiq fetches a job from the set of queues `critical, default, bulk`, it uses `BRPOP critical default bulk` because it expects all queues to be available in that remote redis. We can't spread those queues across a cluster.

As you note, we could prefix all global structures to force them onto one cluster member (e.g. `{1}:default`) which becomes the "primary" node but that's just busywork, now we're back to a single point of failure.

There are a few subsystems which can benefit from hash tagging. Rate limiting is a perfect example of a subsystem which is standalone and, with minor exceptions, does not have "global" data so we can cluster it for a nice scalability win. But everything else I can think of needs to interact with queues and needs a primary Redis so Sidekiq can use transactions. For instance it would be nice to make batches cluster-friendly but we have to push batch jobs into queues and update batch metadata as one transaction to ensure consistency.

**Comment by mperham** [comment]
I'd encourage you to re-examine your demand for absolute data reliability. There's no system in the world that is 100% reliable. Every system can be misconfigured or have data loss bugs. What data do you have that shows Sidekiq does not meet this threshold?

For instance, someone [recently posted][0] that they enqueued 350 million jobs and detected that two jobs were lost, or 99.999999% reliability. Eight nines, and Sidekiq Pro should catch those last two. What data do you have to show that any other system is more reliable than that? Systems, networks and client libraries have bugs. A perfect system *in theory* could provide way less reliability in practice.

In my experience, the most reliable system *in practice* is the one which is heavily used: the happy path is smooth and well-paved.

[0]: https://news.ycombinator.com/item?id=35570301

**Comment by mperham** [comment]
Can you use Sidekiq 6.5.x if possible?

You are using [redis 4.5.1](https://github.com/redis/redis-rb) which is not a cluster-aware client. You need to use a [different gem](https://github.com/redis/redis-rb#cluster-support), which I assume can handle the `MOVE` command.

**Comment by lorrin** [comment]
Awesome, that works! The redis-clustering gem got introduced with redis-rb 5, so not directly applicable, but that put me on the right path. In [redis-rb 4](https://github.com/redis/redis-rb/tree/v4.8.1), I just needed to initialize with `redis.config = { cluster: [url], namespace: "{0}" }` instead of `redis.config = { url: url, namespace: "{0}" }`.

What options are there going forward? I see that Sidekiq 7 replaces redis-rb with redis-client, and the redis-namespace gem is specific to redis-rb, and that the removed namespace support required Sidekiq to [explicitly invoke the redis-namespace gem](https://github.com/sidekiq/sidekiq/commit/f22a1c27c76f8fd7ba1fc9d36ad3be9145cd5c9f).

I think Sidekiq uses relatively few keys? It might be more straight-forward to put logic in the Sidekiq key name generation than to revive the approach of wrapping the redis client in a general purpose transparent namespace injector the way redis-namespace did.

**Comment by mperham** [comment]
> What options are there going forward?

There's no demand for this except you right now. You can stay on Sidekiq 6 for the next year or two and see if MemoryDB gets more uptake. But I'd point out that using Sidekiq in a non-standard way so you can get "more reliability" might be an oxymoron. In my experience, stay on the happy path.

If I were implementing this, I'd lean in the direction of building namespace support into sidekiq/redis_client_adapter.rb, almost every Redis command goes through the RedisClient `call` method so maybe you can prefix the second arg but it's likely more complex than that.

**Comment by jimjh** [comment]
I am interested in using Sidekiq with AWS MemoryDB as well. I am not worried about the _uptime_ of Elasticache, but we ran into a situation where our Elasticache cluster's memory filled up, it froze, and there was nothing we could do except restart the nodes. Sidekiq workers were also unable to remove jobs from the queues. As a result, all sidekiq jobs that were still in queues on Redis were lost.

We're still working with AWS to figure out what happened.

Our main reason for looking into AWS MemoryDB: don't lose data in these queues.

I am also considering using Redis hosted by Redis.com, but that's operationally more challenging since it requires a separate VPC, and they have yet to build support for PrivateLink. Our only option is VPC Peering, which leads to other issues we would have to deal with.

**Comment by ouranos** [comment]
We placed AWS MemoryDB on our backlog when it was announced, primarily due to its limited availability with only larger nodes and other competing priorities. Now that we are in the process of upgrading to Sidekiq 7, we're reassessing our Redis configuration and considering using AWS MemoryDB.

As per the others, our main concern is durability as ElastiCache durability is "best effort" as it's primarily designed for caching purposes.

> For Redis nodes, the replacement process is designed to make a best effort to retain your existing data and requires successful Redis replication. 

_https://aws.amazon.com/elasticache/elasticache-maintenance/_

> The Amazon ElastiCache for Redis engine upgrade process is designed to make a best effort to retain your existing data and requires successful Redis replication.

_https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html#VersionManagement-upgrade-considerations_

We've been using Sidekiq on ElastiCache for Redis for a while and it's been rock solid, our only concerns are:
- As per the James experience, we had an incident where the queues filled up (due to some infrastructure issue) and Redis ran out of memory. The on-call engineer rebooted the nodes since nothing else was working and it lost all the queues. (We now use larger Redis instead and have lowered the alert threshold to mitigate this).
- During Redis upgrade/maintenance, there's always a chance of data loss (as per above)

For now, we'll upgrade our ElastiCache instance to the latest Redis version and keep monitoring this issue.
