### ISSUE TITLE
Update from 7.1.0 to 7.1.1 breaks Sidekiq Enterprise auth

### ISSUE THREAD

**Issue by axelerator** [sidekiq/sidekiq#5933]
We have dependabot doing patch version upgrades of the `sidekiq` gem and then our job workers don't come up in production with the following error. Rolling back to version `7.1.0` fixes the problem.

We pass our credentials through the Gemfile(see below). Is that not supported anymore?

```
ArgumentError:
   WARNING WARNING WARNING WARNING WARNING WARNING WARNING
Sidekiq Enterprise requires valid license credentials in order to run.
You can set the Bundler credentials in the environment as documented
in your access instructions, e.g.:
   bundle config enterprise.contribsys.com abc12345:password
or, if you are running in a high security environment where you don't
wish to configure Bundler credentials, set a special env variable
to the credential username:
   SIDEKIQ_ENT_USERNAME=abc12345 bundle exec sidekiq ...
```

Ruby version: 3.2.1
Rails version: 7.0.5
Sidekiq / Pro / Enterprise version(s):  7.1.0 

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```
# initializer
require 'shopify-cloud/canonical_logging/sidekiq'

REDIS_URL = Rails.env.development? || Rails.env.test? ? ENV.fetch('REDIS_URL', nil) : ENV.fetch('REDIS_JOBS_URL', nil)

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_client { |config| config.redis = { url: REDIS_URL } }
Sidekiq.configure_server do |config|
  config[:job_logger] = ShopifyCloud::CanonicalLogging::Sidekiq::JobLogger
  config.redis = { url: REDIS_URL }

  config.super_fetch!
  config.reliable_scheduler!
end
```

```
# sidekiq.yml
---
:concurrency: 3
:queues:
  - high_priority
  - default # ApplicationJob/ActiveJob default
  - mailers
  - medium_priority
  - low_priority # SidekiqJob default
  - pausable # Jobs added to the pausable queue can be repetitively delayed.
```

```
gem 'sidekiq', '~> 7'
gem "sidekiq-ent", '~> 7', source: "https://XXXX:XXXXX@enterprise.contribsys.com/"
```

> If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?
yes

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Hi Axel, the canonical way to configure Bundler for gem access is like this:

```ruby
gem "sidekiq", "<8"
source "https://enterprise.contribsys.com" do
  gem "sidekiq-pro"
  gem "sidekiq-ent"
end
```

and then using `bundle config enterprise.contribsys.com user:pwd` to store your credentials. I don't support putting credentials in the Gemfile like that but it happened to work until 7.1.1.

**Comment by javierjulio** [comment]
I just noticed this same error after updating Sidekiq from 6.5.8 to 6.5.9. We have an Enterprise license so our Gemfile looks like you shared but no credentials in the Gemfile and we are noticing the same error reported in our staging environment.

**Comment by axelerator** [comment]
Yeah I'm also wondering how the credentials get communicated in production now since `bundle config` exclusively modifies the local bundler config on my machine.

How do the credentials go into my production container?
Or do I have to go down the `SIDEKIQ_ENT_USERNAME=abc12345 bundle exec sidekiq ...` road?

This also only seems to set the "username", won't that choke on the missing "password"?
Also happy to take any pointers on docs 🙏

**Comment by mperham** [comment]
`bundle config` has the `--local` mode which will save project-specific variables to `.bundle/config`. You can also set `BUNDLE_ENTERPRISE__CONTRIBSYS__COM` as noted in the access email you received upon purchase.

**Comment by pre** [comment]
I'm also trying to find out what's needed after Sidekiq 7.1.0 update to 7.1.1.

I get the same error (warning) which crashes Sidekiq. 

I can
```
 curl -I https://user:pass@enterprise.contribsys.com/gems/sidekiq-ent-2.2.3.gem
HTTP/1.1 200 OK
```

Gemfile has 
```
source "https://user:pass@enterprise.contribsys.com/" do
  gem 'sidekiq-pro'
  gem 'sidekiq-ent'
end
```

The 7.1.1 patch release notes didn't see dangerous in comparison to 7.1.0 but this problem does not happen in 7.1.0.

**Comment by mperham** [comment]
@pre You need to configure Bundler with your gem server credentials. You do that with `bundle config`.  https://bundler.io/v2.4/man/bundle-config.1.html

The Enterprise 2.0 release notes mention this requirement. https://github.com/sidekiq/sidekiq/blob/main/docs/Ent-2.0-Upgrade.md#whats-new

**Comment by axelerator** [comment]
Setting `BUNDLE_ENTERPRISE__CONTRIBSYS__COM` solved it for me. The format is the `username:pw` as in the other places.

Having to rely on the content that was sent to an enterprise (potentially years) ago makes it really hard to set up things correctly. Unless there are some security concerns it would be great if this would be documented somewhere closer to the top level.

**Comment by pre** [comment]
> The Enterprise 2.0 release notes mention this requirement. https://github.com/sidekiq/sidekiq/blob/main/docs/Ent-2.0-Upgrade.md#whats-new

These release notes say: ” If you configured Bundler as described in the access email you need do nothing” . 

Which is true: we did nothing akf everything worked still in Sidekiq 7.1.0

The problem came with Sidekiq 7.1.1 which started crashing instead. The Sidekiq 7.1.1 have no mention of this change. 

The release changelog refers to an email which eg I have never personally seen. Our organization has licensed Sidekiq maybe 10 years ago, hence referring to instructions in an old email doesn’t feel appropriate.

**Comment by mperham** [comment]
@pre I understand your point. The issue is that you do not have Bundler configured. If you did, it should not throw that error. 7.1.1 fixed an issue which prevented the validation of the Bundler configuration requirement and that's why you're seeing the error now.

Here's a page with more instructions:
https://github.com/sidekiq/sidekiq/wiki/Comm-Installation#sidekiq-enterprise

**Comment by mlangenberg** [comment]
We also ran into this issue at our company and noticed that before Sidekiq 6.5.9 / 7.1.1. Sidekiq.options[:environment] was always nil. This caused the license check to be skipped, because this only runs for the production environment.

Now that the environment is actually set with this patch release, we found out the hard way that the BUNDLE_ENTERPRISE__CONTRIBSYS__COM environment variable has never been properly set, because Sidekiq workers refuse to start.

Setting the bundle config is the proper fix, but the timing of it all was unexpected.

See also #5941.

**Comment by madleech** [comment]
@mperham I repeat my advise from #5941:
> At a minimum, I'd suggest running the license check on any non-local (i.e. development or test) environment. That way the issues will show up **before they hit production**.

Personally I fail any PR that includes production-only environment checks, it's a disaster waiting to happen. See e.g. above comments.

While the instructions clearly state what needs to be done, we're only human and occasionally slip up. That's why we have integration environments, so that we can catch these slip-ups before they're deployed.
