### ISSUE TITLE
v7.1.1 can break production environments due to fixes to the license check.

### ISSUE THREAD

**Issue by ioquatix** [sidekiq/sidekiq#5941]
The Sidekiq v7.1.1 copies `RAILS_ENV` into `Sidekiq.options[:environment]`.

- https://github.com/sidekiq/sidekiq/issues/5932
- https://github.com/sidekiq/sidekiq/blob/5e1a77a6d03193dd977fbfe8961ab78df91bb392/Changes.md?plain=1#L16

The license check for Sidekiq enterprise depends on that configuration variable, and only checks the license if `Sidekiq.options[:environment]` is "`production"`.

```ruby
Sidekiq[:environment] == "production" && !Bundler.settings["enterprise.contribsys.com"] && !ENV["SIDEKIQ_ENT_USERNAME"]
```

Unfortunately, this is not obvious when running in non-production environments. So you do all your testing in staging/integration and everything looks great, then you deploy to production and it stops working.

I respect that we probably should have been more aware of the warnings, but I just want to point out that this caused an operational outage on our end and I'm sure it will affect others too.

I would suggest that you make this fail in non-production environments too, or at least issue a warning in those cases too.

**Comment by madleech** [comment]
Expanding on this:
* Before this change, the `sidekiq-ent` license check would be skipped because the `environment` option would evaluate as `nil` since `RAILS_ENV` was being set but not `APP_ENV` etc.
* This was pretty hard to track down, since a ..1 release generally doesn't break anything, and the failures were coming from `sidekiq-ent` gem which hadn't been changed in quite a while. 
* The breakage was only happening in production and not integration, even when running identical code.

At a minimum, I'd suggest running the license check on any non-local (i.e. development or test) environment. That way the issues will show up before they hit production.
