### ISSUE TITLE
Periodic Jobs queue option is ignored for ActiveJob

### ISSUE THREAD

**Issue by dedman** [sidekiq/sidekiq#6099]
Ruby version: 2.7.6
Rails version: 7.0.6
Sidekiq / Pro / Enterprise version(s): 7.2.0 (Ent)

I'm migrating to using periodic jobs after we recently purchased enterprise, and we have a mix of ActiveJob style jobs and Sidekiq style jobs. I noticed during testing locally that the ActiveJob style jobs don't get put in the correct queue when they are configured to be periodic jobs. 

The following initializer and classes should allow you to replicate the issue. In my local environment the AbcWorker is created in the `high_priority` queue, but the AbcJob is created in the `default` queue.

```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }
  config.periodic do |manager|
    manager.register('* * * * *', 'AbcWorker', queue: :high_priority)
    manager.register('* * * * *', 'AbcJob', queue: :high_priority)
  end
end
```

```
class AbcWorker
  include Sidekiq::Worker

  def perform
    puts "ABCWorker.perform"
  end
end
```

```
class AbcJob < ActiveJob::Base
  def perform
    puts "ABCJob.perform"
  end
end
```

Is this something you would consider a bug? I read [this part](https://github.com/sidekiq/sidekiq/wiki/Active-Job#commercial-features) of the wiki about the commercial features not necessarily working with ActiveJob, but the [wiki also mentions](https://github.com/sidekiq/sidekiq/wiki/Ent-Periodic-Jobs#notes) that ActiveJob is supported by the periodic feature as of Sidekiq 7.1. We are planning on migrating all of our jobs away from ActiveJob in the not too distant future, but we were hoping not to have to do it just yet :)

**Comment by mperham** [comment]
This is one of those edge cases that I don't control and why I disclaim perfect compatibility with ActiveJob. ActiveJob does not support String keys for its job options:

```ruby
SomeJob.set(queue: "foo").perform_later # => foo
SomeJob.set("queue" => "foo").perform_later # => default
```

The periodic manager calls `SomeJob.set(periodic_options).perform_later` but because those options have been normalized into a Hash of <String,JSONObject>, ActiveJob fails to work with the String key. I will add `with_indifferent_access` to that Hash so it will work better with Rails/ActiveJob.
