### ISSUE TITLE
Payload field inside work from Sidekiq::WorkSet is not hash anymore

### ISSUE THREAD

**Issue by YJorge** [sidekiq/sidekiq#6145]
Sidekiq version(s): 7.2.0

In accordance with your documentation  https://github.com/sidekiq/sidekiq/wiki/API#workers 
payload inside work should be hash
<img width="552" alt="image" src="https://github.com/sidekiq/sidekiq/assets/81574649/28b259ab-fd9e-4372-ae6a-e2fe8d77cb14">

But in https://github.com/sidekiq/sidekiq/commit/ad9442f116086424948d60ec059755f9168a6bc8 it was changed to json.

`work` in Sidekiq 6.5.10
<img width="562" alt="image" src="https://github.com/sidekiq/sidekiq/assets/81574649/04360dec-475c-441a-9741-fc27b898184c">

`work` in Sidekiq 7.2.0
<img width="716" alt="image" src="https://github.com/sidekiq/sidekiq/assets/81574649/7e718b76-0fa8-4063-95de-9fd212213ed8">

**Comment by mperham** [comment]
This was changed as part of the 7.0 major bump. The payload in Redis now refers to the raw job string to minimize runtime JSON serialization overhead.

The real issue here is that we're using bare Hashes instead of a type which we can control and use to maintain backwards compatibility. Let's add a Work type which quacks like a Hash for backwards compat.

**Comment by mperham** [comment]
7.2.1 has a refactoring of this code so it will warn with the old-style API and provide a new-style API going forward. See the changelog notes.
