### ISSUE TITLE
Need details of what happens to running jobs during Shutdown

### ISSUE THREAD

**Issue by nhorton** [sidekiq/sidekiq#6213]
This is selfishly for Sidekiq Pro but I think it applies to all the others.

On https://github.com/sidekiq/sidekiq/wiki/Deployment, it says 
> "If any jobs are still running when the timeout is up, Sidekiq will push those jobs back to Redis so they can be rerun later". 

But what does that actually mechanically mean? 

1. Is that a Sidekiq retry that goes back? Or is it actually put straight into the queue again?
2. It looks like a Sidekiq::Shutdown is sent to each thread - is that correct and the intended behavior? Right now, that is triggering Rails after_discard callbacks since that is a descendant of Interrupt and nothing on the Rails side will catch that (somewhat by design).
3. Is there any other signal allowed through that would go to sub-processes we have started? Or do we need to catch the Sidekiq::Shutdown, send a TERM to child processes, then reraise the Shutdown?

**Comment by mperham** [comment]
I don't document this because it starts to get into implementation detail. Anything I document becomes behavior I have to support and maintain backwards compatibility with.

1. It pushes the raw job payload back to the front of the queue; the job will be restarted ASAP.
2. Yes, for jobs which run past the shutdown timeout, 25 seconds. Most jobs should finish within the timeout. A gem like `sidekiq-iteration` can help you with long-running database jobs.
3. I'm not an expert in Ruby's signal handling semantics with child processes, I can't answer this with confidence. If your child process is long-running, seems like this might be necessary but that's speculative on my part.

**Comment by nhorton** [comment]
Thanks for the info on this. I think #2 might be worth the documentation because the behavior is effectively "jobs disappear if they did not stop in time" because that Sidekiq::Shutdown exception won't be one that any standard handlers deal with.

**Comment by mperham** [comment]
Could you explain more? Long running jobs are pushed back to Redis by `Sidekiq::Manager`.

**Comment by nhorton** [comment]
@mperham - sorry, I thought I responded. 

There are two reasons I say that. 

1. We still have anecdotal experiences with jobs disappearing, and this seems related
2. We see after_discard Rails callbacks happen when the Sidekiq::Shutdown events have fired, so Rails thinks they are discarding.  I suspect that is because the Sidekiq retry mechanism is a new job in Rail's sense?

Closely related in all this is that we just get a ton of questionable behaviors around Sidekiq in shutdown situations. For example, we had an instance get hard-killed earlier today, and 2 hours later the jobs it was doing are still showing in the UI as being in progress. The jobs were indeed re-enqueued and are happening on another machine as well, but even 2 hours later the working set status is incorrect.

**Comment by mperham** [comment]
...and that leakage is now fixed on main.
