### ISSUE TITLE
Upgrade Bootstrap CSS

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6222]
https://getbootstrap.com

Today Sidekiq is using v3.3.7 from 2016. v5.3 is the latest.

- [ ] Upgrade .css files to 5.3.x
- [ ] Upgrade .erb files with latest Bootstrap styles (e.g. hamburger, navbar and footer)
- [ ] Trim down application.css
- [ ] Verify iPhone/mobile/small
- [ ] Verify iPad/tablet/medium
- [ ] Verify laptop/desktop/large
- [ ] Take screen shots of different tabs and different browser page sizes so you can show before/after.

We don't use or want any Bootstrap javascript.

**Comment by mperham** [comment]
I've added a task to trim down application.css. Today's it's ~750 lines but I'd like to trim that down as much as possible. Let's prune or DRY up our styles as much as possible.

**Comment by karloscarweber** [comment]
Hi Friend,

I'm Karl. A Designer and developer of digital stuff. I've been making apps and websites for 13 years. All that time also making websites. I can help you.

The goal is to move to a new front end system or Sidekiq without using a large CSS framework or any Javascript. While maintaining accessibility, multiple languages, and RTL language support. In Modern times, which sounds silly but the web is like 30 years old now, building something new, great, and small, is not difficult, for a few reasons:

1. Modern CSS Layout frameworks offer simple and easy ways to adopt RTL language support without writing conditional layout code.
2. Accessibility issues arise from entirely avoidable architecture decisions such as using a SPA framework etc..
3. Javascript frameworks are entirely unnecessary to achieve great interface fidelity and compatibility. Many slick or delightful UI experiences are achievable with just a bit of CSS.

You don't need a large CSS framework but you DO need a simplified component Library & clear composition guidelines. (How to assemble A page with these components, modifiers, customization, etc...)

BIG PICTURE _ Everything built needs to be built into a flow layout structure, every section needs clear headers & section skip links for accessibility.

Great user ergonomics is of paramount importance.

The deliverables of this project should be a small CSS file, A web component library, A Docs site that has numerous examples & guidance, and ERB or Phlex components ready to use. Everything would be open source, which would be badass and extremely awesome.

My Offering: I provide Art, Design, & Engineering services to companies, small to medium, and startups. My emphasis is Art, Design, and UI across the web and iOS. I sell these partnerships as subscriptions through my studio [Capsule](https://capsule.graphics).
I perform as much work as I can in a month. I don't sell hours, but I track them internally to ensure I provide a minimum level of focus for each client.

I sell 3 plans:
* Rocket - Art, Design, & Web. $999/month
* Pro - Like Rocket, plus Ruby & iOS development. $1,999/month
* Bell Grande - Like Pro, only 3 times larger, more focus, and extra meat & sour cream. $5,999/month

I think that this project, redesigning and upgrading the Sidekiq dashboard HTML/CSS implementation, would take 3-5 months. The deliverables would be A whole pile of CSS and HTML, an extensive documentation site with copy-pastable code examples for everything, and a warm fuzzy feeling in your heart. I could also implement all of the HTML and CSS into Sidekiq itself but this requires a Pro plan. Also The whole project could be delivered much faster with a Bell Grande plan.

Capsule is a new studio offering, I organize myself to prioritize delivering true value to my customers and treating them like partners. I'm highly proactive and will do almost anything to make you happy.

I know that it may seem like a much larger project than just upgrading bootstrap, but CSS is not easy, and bootstrap is, well... a bootstrap. Great results come from intentional actions and focus over time, and that's what I hope to provide. Focus on helping you any way I can.

Anyways, I hope all is well with you, and that you find what you're looking for. 

Sincerely,
Karl Oscar Weber

**Comment by mperham** [comment]
Sadly, this has turned out to be unworkable.

* Bootstrap 3 has never supported RTL, our RTL support is based on a [user-supplied theme](https://github.com/morteza/bootstrap-rtl) for Bootstrap 3.x.
* RTL support in Bootstrap 5 requires us to ship two different Bootstrap CSS files and dynamically include one or the other at runtime.
* Dark mode support in Bootstrap 5.3 requires explicit user activation via a UI element and JS. This is a terrible decision IMO, it's unclear why they can't just gate everything behind `prefers-color-scheme`. Here's their recommended [100 lines of JS](https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript) just to support `prefers-color-scheme`.
* Navbar CSS has changed significantly, requiring an overhaul of the header and footer.

I still want to spend some time finding and removing extraneous CSS rules but for now it looks like we're stuck on Bootstrap 3.
