### ISSUE TITLE
Efficient job search

### ISSUE THREAD

**Issue by jgutierrez-ats** [sidekiq/sidekiq#6257]
I would like to find a job given a queue name. I am aware that [this method](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/api.rb#L296-L307) exists, but it not recommended to use under normal conditions. 

**Q: What is the best and most performant way to find a job within a specified queue regardless of a job's state?** 

Thank you in advance.

**Comment by mperham** [comment]
Are you looking to scan an actual queue, e.g. a Redis list, or the Scheduled/Retry/Dead sets, e.g. a Redis sorted set? There is completely different answer for each.

**Comment by mperham** [comment]
There is no helper method for Lists (queues) because there's no efficient Redis operation. I don't make it easy because list scans are so slow. That `find_job` method literally pulls all list data into Ruby, parses it and checks each JID -- very slow.

Sorted sets can be scanned efficiently, see Scanning and Filtering on this blog post:

https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/

That's why there's a Filter textbox in the Web UI on e.g. the Retry page but none on the Queue page.

**Comment by jgutierrez-ats** [comment]
@mperham Thank you for following up. I believe you pointed me in the right direction. Thanks!
