### ISSUE TITLE
Feature request: add flag to opt in/out of Process.warmup

### ISSUE THREAD

**Issue by dgollahon** [sidekiq/sidekiq#6279]
I have been trying to debug a memory leak on ruby 3.3.x and it would have helped me to be able to toggle it on and off temporarily to see if it was part of the problem. I have seen a number of issues on various repos indicating that they had odd behavior with native extensions with `Process.warmup` I believe related to GC compaction. It's still unclear if it was a contributing factor to the behavior I saw or not but I'd like to be able to configure this in any case.

Thanks!

**Comment by mperham** [comment]
You can disable warmup by calling `cli.run(warmup: false)` in `bin/sidekiq`. I don't see a need to make it any easier but you're welcome to make the case if you feel otherwise.

**Comment by dgollahon** [comment]
> You can disable warmup by calling cli.run(warmup: false) in bin/sidekiq.

Sorry, when you say in calling that in `bin/sidekiq` how do you suggest users do that? Are you suggesting I edit the `sidekiq` "binary" to change this and/or fork sidekiq? I would assume most people would launch sidekiq like the docs show by calling the executable and optionally passing it a config file: https://github.com/sidekiq/sidekiq/wiki/Advanced-Options#the-sidekiq-configuration-file

**Comment by mperham** [comment]
Copy bin/sidekiq to bin/sidekiqcold in your app, add the flag and run your testing. You’re just hacking this together to debug.

**Comment by dgollahon** [comment]
> You’re just hacking this together to debug.

I am suggesting this as a long-term opt-out which I think people would like to be able to do (at least, I would like to be able to do--particularly deploying in this state) but I can work around this...

It just seems slightly aggressive to turn it on by default and not have an opt-out other than doing something very strange/hacky. That's just my $0.02.

**Comment by mperham** [comment]
I don't think of it as aggressive at all. Ruby documented its purpose and I don't recall hearing any drawbacks or danger in doing so. I added that `warmup` flag to be cautious but I don't think it's a good idea for anyone to opt-out long-term. It's a valuable point in time for the Ruby runtime to perform optimizations.

**Comment by andrewhampton** [comment]
Our investigation is still underway, but we started seeing an issue in production where turning this off seems to have solved our problem.

We started seeing an issue where LaunchDarkly API calls would return `FLAG_NOT_FOUND` errors. It's still not clear to us if turning this off actually fixes the issue, or just changes timings enough to sidestep some race condition.

I agree that no opt-out makes sense if this is a stable change for most people. So just leaving a comment here as a single counter-example.

Also, just in case anyone else runs into this and needs to maintain a custom copy of `bin/sidekiq`, here's a spec that will fail when a release comes out with `bin/sidekiq` changes:

```ruby
require 'rails_helper'

describe 'sidekq binary' do
  it 'should match the last validated file hash' do
    # last verified md5 hash of the sidekiq bin file
    expected_hash_value = "63e6c20e28e96a92442bf795998d4093"

    # get the sidekiq gem path using bundler
    bin_path = "#{Bundler.rubygems.find_name('sidekiq').first.full_gem_path}/bin/sidekiq"
    current_hash_value = Digest::MD5.file(bin_path).hexdigest

    # If this test fails, it means the last known MD5 hash value for the sidekiq bin file has changed.
    # This likely means the sidekiq bin file in our bin/ directory is out of date.
    # To fix this, you'll need to go assess the changes to the sidekiq version of the bin file
    # and make the appropriate updates to our bin file. After that, update the
    # expected_hash_value above to match the new file.
    expect(current_hash_value).to eq(expected_hash_value)
  end
end
```

**Comment by daande** [comment]
@mperham We recently bumped:

sidekiq-ent (7.2.1) -> sidekiq-ent (7.2.4)
sidekiq-pro (7.2.0) -> sidekiq-pro (7.2.1)
sidekiq (7.2.1) -> sidekiq (7.2.4)

We encountered a spike in `Super fetch called.` seen here:

<img width="1764" alt="image" src="https://github.com/sidekiq/sidekiq/assets/3680231/d4039a0f-308d-41fd-9cb1-a7c50adccf23">

In past experience on our platform this is due to containers running OOM and rebooting. 

We reverted the version bumps and everything is running back to normal, please advise?

**Comment by daicoden** [comment]
We just had a 2 day incident because of this change when we bumped to 3.3. Very subtle failures in production.

**Comment by evanlok** [comment]
We also ran into issues with this, specifically around evaluating launch darkly feature flags. Luckily we were able to catch it before it reached production otherwise it would have caused a huge fire. This should have been an opt in feature until it was confirmed stable or been a major version bump with an opt out option so people were aware of this change.

**Comment by mperham** [comment]
No one has actually explained what the underlying issue is. Why was LaunchDarkly broken by this?

**Comment by evanlok** [comment]
@keelerm84 and the LD team might know more? Given that no one has been able to figure out a root cause for this and the other issues mentioned here makes me think this should be opt in until this is solved.

**Comment by mperham** [comment]
Looks like you can add this to your sidekiq.rb initializer until they fix the linked issue:

```ruby
Sidekiq.configure_server do |config|
  config.on(:startup) do
    # Re-initialize LD...
  end
end
```

https://github.com/launchdarkly/ruby-server-sdk/issues/282

**Comment by evanlok** [comment]
I disabled warmup by creating a custom binstub as mentioned above. While the LD workaround seems to work, I'm still hesitant to turn it back on until the root cause is determined because we don't know what else this might impact. I'd much prefer if this was an opt in feature of sidekiq so others don't run into similar issues when they upgrade to Ruby 3.3. I think stability is more important than the small performance improvements that this might provide.

**Comment by keelerm84** [comment]
> @keelerm84 and the LD team might know more? Given that no one has been able to figure out a root cause for this and the other issues mentioned here makes me think this should be opt in until this is solved.

Sorry for the delay in response here.

I believe I have a fix for this issue, which has been released as [v8.8.1](https://github.com/launchdarkly/ruby-server-sdk/blob/main/CHANGELOG.md#881-2024-10-30). 

The issue seems to be the way we are indexing into our memory store. The hash key used is itself a hash, including a couple of simple properties, and in the case of flags, a lambda. After `Process.warmup`, that hash key no longer reliably indexes the store, unless `rehash` is called first on the store. Removing the lambda from the key also seems to fix the issue.

**Comment by evanlok** [comment]
@mperham Now that this is a confirmed [Ruby bug](https://bugs.ruby-lang.org/issues/20853) in versions < 3.3.6, can you change `Process.warmup` to only be called in versions 3.3.6 or higher?

**Comment by mperham** [comment]
@evanlok Why? The bug has been fixed in both Ruby and in the LaunchDarkly gem. You can upgrade one or the other.

**Comment by evanlok** [comment]
Mainly as a precaution for those that aren't on Ruby 3.3.6 yet. I suspect gem upgrades occur more often than Ruby upgrades. If we know something is broken on certain versions of Ruby does it make sense to continue using it on those versions?

**Comment by mperham** [comment]
That implies that puma, pitchfork, good_job, solid_queue and every other app container calling `warmup` needs to do the same. I'm not sure that's reasonable. Mysterious bugs suck.

I did realize that I'm calling `warmup` in the wrong place since it's designed to be called before fork. I'll see if I can make this better while fixing this.

**Comment by daicoden** [comment]
We rolled this out on ruby 3.3.5 with the launch darkly upgrade on 8.8.1 and everything is fine.

**Comment by daande** [comment]
> [@mperham](https://github.com/mperham) We are running on Ruby 3.3.3 and we recently bumped:
> 
> sidekiq-ent (7.2.1) -> sidekiq-ent (7.2.4) sidekiq-pro (7.2.0) -> sidekiq-pro (7.2.1) sidekiq (7.2.1) -> sidekiq (7.2.4)
> 
> We encountered a spike in `Super fetch called.` logs as seen here (right after the deploy):
> 
> <img alt="image" width="1764" src="https://private-user-images.githubusercontent.com/3680231/343581403-d4039a0f-308d-41fd-9cb1-a7c50adccf23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzNDEyMzksIm5iZiI6MTczODM0MDkzOSwicGF0aCI6Ii8zNjgwMjMxLzM0MzU4MTQwMy1kNDAzOWEwZi0zMDhkLTQxZmQtOWNiMS1hN2M1MGFkY2NmMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMzFUMTYyODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZmOGVlMjkwMGMwZGQzMWI0Yzg5ZGY5YmFjOTI4NGY5MGJmOWEwMjU1NTBjY2I4MjFlYjBiN2Q0ZGRjNGViYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.h_u7AnJyrRJZ2r1l9BswtrdIM2h0G48A_wx6iWtXbuo">
> In past experience on our platform this is due to containers running OOM and rebooting.
> 
> We reverted the version bumps and everything is running back to normal, please advise we think it could be related to the `Process.warmup` change?

Wanted to give an update that we rolled out the latest Sidekiq versions with no issues on:

Ruby 3.4.1
Rails 8.0.1
Sidekiq 7.3.8
Sidekiq-pro 7.3.5
Sidekiq-ent 7.3.4
launchdarkly-server-sdk 8.8.2
