### ISSUE TITLE
Feature Request: Additional Colorblind-friendly Web UI Colors

### ISSUE THREAD

**Issue by jrgifford** [sidekiq/sidekiq#6387]
Ruby version: 3.1.5
Rails version: 6.1.x
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.3.0 / Pro 7.3.0 / Ent 7.3.0

Follow up to #3387 . 

For some folks with Protan red/green colorblindness (about 4% of the population), the success & pending colors are very difficult to differentiate (hi, I'm some folks. I spent an embarrassingly long time looking at this progress bar during an incident this morning and discovered this).

Suggested change is to apply the `progress-bar-striped` class to the success, which would look like this:

![CleanShot 2024-08-02 at 05 57 28@2x](https://github.com/user-attachments/assets/7077ec85-bd37-404e-a4ec-efdce8602c06)

**Comment by jrgifford** [comment]
other idea:

Put the percentages in a column on the batches overview/list page:

![CleanShot 2024-08-02 at 06 17 28@2x](https://github.com/user-attachments/assets/5c55cc0d-2a48-4d6f-926d-0190767a7213)



and in the parenthesis on the batch details page 

![CleanShot 2024-08-02 at 06 15 23@2x](https://github.com/user-attachments/assets/c3cbb0a7-780d-45b9-8569-aa1e39b51d46)

**Comment by mperham** [comment]
Good catch, thanks. If `striped` is on both the red and the green, wouldn't that be impossible to tell apart, especially when pending is 0? That's why it's only on the red right now.

Side note: have you tried color blind glasses? I don't have any color blindness that I'm aware of but I've heard good things. https://enchroma.com
