### ISSUE TITLE
Dead queue stuck in retry loop after hitting "Retry All"

### ISSUE THREAD

**Issue by eileen-jiang** [sidekiq/sidekiq#6481]
Ruby version: 3.2.5
Rails version: 7.1.4.1
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 5.5.8

Dead queue sometimes gets stuck in a retry loop after hitting "Retry All" from the Dead page on Sidekiq UI. The dead jobs are enqueued & run, end up in the dead queue, then enqueued again on repeat.

I believe this is because [retry_all](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/api.rb#L843-L847) loops while the [size of the dead queue](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/api.rb#L620-L623) is > 0. This means that the initial jobs running could fail and go back to the dead queue before the later jobs get run.

Reproducing on Rails console:
```
> dead_set = Sidekiq::DeadSet.new
=> #<Sidekiq::DeadSet:0x00007fb0edb85330 @_size=51, @name="dead">
> while dead_set.size > 0
     dead_set.each do |job|
       job.retry
     end
     print "."
   end
...........=> nil
```

**Comment by mperham** [comment]
Brainstorming here...

Since the score of any new entries to the Dead set should be strictly larger than any existing score, we should be able to add logic like "break after enqueuing N elements" where N is the size at the start of the loop, instead of looping until size = 0.

PRs welcome, I'm working on Faktory right now.

**Comment by eileen-jiang** [comment]
Aren’t we already looping through each job and calling retry? Why can’t we just get rid of the size > 0 check?

**Comment by mperham** [comment]
We're mutating a data structure while simultaneously iterating through it. Lots of room for data races and footguns here.

Since this is a relatively straightforward thing to test, I think we should create an integration test which exercises this case so we can test and verify the current semantics. There should be something close to that already in `test/api_test.rb`.

**Comment by mperham** [comment]
The size check is because iterating while mutating is unpredictable. If we remove an element, all other elements shift their index so we can't effectively use a cursor.

We could iterate backwards from the "tail" of the structure and use indexes to remove the tail element. That will only fail if another entry is pushed into the middle of the structure: unlikely for the dead set but quite common for the scheduled set.

I just tested and verified that using `each` breaks (retrying each job causes 500 out of 1000 jobs to be retried) but using `reverse_each` works exactly as expected. Unfortunately reverse_each loads the entire dataset into memory first. 😭 No easy solution yet.

**Comment by mperham** [comment]
I would suggest the easiest and best long-term choice is to rewrite these APIs to use ZPOPMIN[0], which we couldn't use until Sidekiq 7.0. Popping one entry at a time effectively rate limits the enqueue process and minimizes any data loss if the network happens to drop right at that instant.

[0]: https://redis.io/docs/latest/commands/zpopmin/

**Comment by mperham** [comment]
Let me know if you have any feedback RE: this PR. ^^^^^^^^^^^

**Comment by eileen-jiang** [comment]
Thanks for looking at this, Mike. We're in the process right now of upgrading to Sidekiq 7. Until we're done with our migration, would you find monkey-patching the Sidekiq::JobSet#each method to be acceptable using the first method you described - breaking after enqueueing N elements?

```
def each
      initial_size = @_size
      offset_size = 0
      page = -1
      page_size = 50
      
      processed = 0 # NEW

      loop do
        range_start = page * page_size + offset_size
        range_end = range_start + page_size - 1
        elements = Sidekiq.redis { |conn|
          conn.zrange name, range_start, range_end, "withscores"
        }
        break if elements.empty? && processed > initial_size # NEW
        processed += elements.size # NEW
        page -= 1
        elements.reverse_each do |element, score|
          yield SortedEntry.new(self, score, element)
        end
        offset_size = initial_size - @_size
      end
    end
```

**Comment by mperham** [comment]
As long as @_size is current, I think that's reasonable.
