### ISSUE TITLE
Statsd missing 'distribution' metric type

### ISSUE THREAD

**Issue by J-Swift** [sidekiq/sidekiq#6534]
Sidekiq / Pro / Enterprise version(s): 7.3.5

I took a look at the source for Sidekiq::Pro::Metrics and it looks like it supports `histogram` but not `distribution`. The two have the same api but have some nuance in the implementation/capabilities. Mainly, histogram coalesces its data client-side instead of server-side which is a lossy operation.

Id like to be able to report using `distribution` to avoid this lossy collection. It looks like a simple copy/paste of `histogram` block will suffice (and I will monkey patch it for now) https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/#distribution.

**Comment by mperham** [comment]
Feel free to email me that monkeypatch. I have a Sidekiq Pro 7.3.4 release pending and this would be nice to get in there.

**Comment by cooljacob204** [comment]
Hi @mperham. Would you have a recommended way to use these new metrics? I assume the changes in 7.3.4 are specifically adding them to `Sidekiq::Pro::Metrics::Dogstatd` but it's not clear to me on how I should implement it. Create a custom server middleware? Basically clone `Sidekiq::Middleware::Server::Statsd` and swap timer for distribution?

**Comment by mperham** [comment]
You should be able to call `metrics.distribution(...)` from any server middleware, or `Sidekiq::Pro.metrics.distribution(...)` from any job.

**Comment by cooljacob204** [comment]
I find the histogram metrics pretty misleading and confusing for Datadog. Even the description is wrong on the Datadog page for `perform.count` https://docs.datadoghq.com/integrations/sidekiq/. It's a count of metrics received, not time spent in workers. Wasted a lot of time trying to make sense of this metric. I opened a ticket with Datadog to fix the documentation.

It was very confusing and took a while to piece this all together that it used histogram. This was brought on by our upgrade to Sidekiq 7 as I was bothered by the fact I couldn't reproduce the metrics page in Datadog and dug in to Sidekiq pro source to figure out why.

A potential nice feature for Sidekiq Pro's Statsd would be some sort of option to use distribution instead of timer. For now I have created my own custom middleware to publish the distribution stats.

**Comment by mperham** [comment]
Ok, I misunderstood. Are you proposing that Sidekiq Pro's instrumentation should use `distribution` instead of `timing` for job perform timing?

**Comment by mperham** [comment]
I believe distribution is a Datadog-proprietary feature, not part of the wider Statsd standard so it may be that you are correct in noting that it has to be optional, rather than the default.

The other issue you called out is that executing 1000 jobs/sec would mean sending 1000 metrics/sec to datadog, rather than aggregating on the client and only sending 1 metric/interval. Another reason to make it opt-in.

I've tried to avoid configuration knobs in Sidekiq so I'm not convinced this is worth the additional complexity but I've made a number of informal patch points where customers can patch the API. Can you easily monkeypatch the behavior or can we make it easy to monkeypatch in S::Pro::Metrics?

**Comment by cooljacob204** [comment]
> Can you easily monkeypatch the behavior or can we make it easy to monkeypatch in S::Pro::Metrics?

So the way I approached it is I just copied the entire statd middleware and swapped out the timer line with distribution. This works fine for our needs right now but runs the risk of deviating from the real one as time goes on.

> can we make it easy to monkeypatch in S::Pro::Metrics?

I think if the timer call was abstracted to it's own method within `Sidekiq::Pro::Statd` it would make monkey patching a lot easier and help us keep our statd Middleware more inline with Sidekiq pro.

And on a side note, after updating from histogram to distribution the metrics are a lot, lot more useful. I don't want to say they were entirely useless before... But comparably they were. I'm a surprised that this hasn't come up more often. This was the only issue/thread I could find in regards to it.

So far I haven't noticed a bump in our Datadog bill with the move.

**Comment by J-Swift** [comment]
Just wanted to chime in on this

> The other issue you called out is that executing 1000 jobs/sec would mean sending 1000 metrics/sec to datadog, rather than aggregating on the client and only sending 1 metric/interval. 

I believe the typical install will already be aggregating + flushing periodically so I'm not sure what the 'real world' difference would be in terms of datadog api calls. Definitely a more frequent flush but I'm not sure what the actual delta might be.

**Comment by mperham** [comment]
I've added new `sidekiq.jobs.perform_dist` and `sidekiq.batches.duration_dist` distribution metrics to Sidekiq Pro, enabled by default and updated the wiki. This will be available in Pro 8.0.2 soon.

https://github.com/sidekiq/sidekiq/wiki/Pro-Metrics
